// ===== Taiao — 3D paperdoll characters =====
// Builds animatable retired prototype Models from voxel part data generated by the
// kenney-shape pipeline (segment 8-direction sprites into parts, reconstruct
// each part as voxels, pack via build_paperdolls.py into
// js/sprites/paperdolls/{safe}.js + paperdoll-manifest.js).
//
// Each character is a set of PART sub-models (head, torso, arms, legs, tail,
// wings, weapons) merged into one LC.Model whose vertices carry the HUMAN
// AnimBase labels (see kenney-shape/tools/anim_labels.json). That makes the
// stock retired prototype animations (stand/walk/run/turn/chop/mine/combat...) drive
// the paperdoll natively through Model.applyTransforms — pivot labels sit on
// thin joint bands, body labels are the rotate-only ones. Parts stay separate
// sub-models in the build, so a future equipment system can swap any slot
// (weapons already are their own slot on the RS weapon label).
"use strict";

const PAPERDOLL_DATA = {};
function PAPERDOLL_REGISTER(safe, data) { PAPERDOLL_DATA[safe] = data; }

const Paperdoll = (() => {
  const modelCache = new Map();   // safe -> { base, height }
  const loading = new Map();      // safe -> [callbacks]

  const safeName = folder => folder.replace(/\//g, "_").replace(/ /g, "_");
  const available = folder =>
    typeof PAPERDOLL_MANIFEST !== "undefined" && PAPERDOLL_MANIFEST.includes(safeName(folder));

  // load a character's data file on demand (script injection works offline)
  function load(folder, cb) {
    const safe = safeName(folder);
    if (PAPERDOLL_DATA[safe]) { cb(true); return; }
    if (!available(folder)) { cb(false); return; }
    if (loading.has(safe)) { loading.get(safe).push(cb); return; }
    loading.set(safe, [cb]);
    const s = document.createElement("script");
    s.src = `js/sprites/paperdolls/${safe}.js`;
    s.onload = () => { const cbs = loading.get(safe); loading.delete(safe); cbs.forEach(f => f(!!PAPERDOLL_DATA[safe])); };
    s.onerror = () => { const cbs = loading.get(safe); loading.delete(safe); cbs.forEach(f => f(false)); };
    document.head.appendChild(s);
  }

  // ---- RS 16-bit HSL packing (hue 6b / sat 3b / lightness 7b) ----
  function rgbToHsl16(rgb, lightScale) {
    const r = ((rgb >> 16) & 0xff) / 256, g = ((rgb >> 8) & 0xff) / 256, b = (rgb & 0xff) / 256;
    const mx = Math.max(r, g, b), mn = Math.min(r, g, b);
    let h = 0, s = 0;
    const l0 = (mx + mn) / 2;
    if (mx !== mn) {
      const d = mx - mn;
      s = l0 > 0.5 ? d / (2 - mx - mn) : d / (mx + mn);
      if (mx === r) h = (g - b) / d + (g < b ? 6 : 0);
      else if (mx === g) h = (b - r) / d + 2;
      else h = (r - g) / d + 4;
      h /= 6;
    }
    // pre-compensate the engine's palette gamma (setBrightness 0.8 brightens
    // everything after quantization): pow(l, 1.25) so displayed ≈ source
    let l = Math.max(0.02, Math.min(0.96, Math.pow(l0 * lightScale, 1.25)));
    let hq = (h * 64) | 0; if (hq > 63) hq = 63;
    let sq = (s * 8) | 0; if (sq > 7) sq = 7;
    let lq = (l * 128) | 0; if (lq > 127) lq = 127;
    // very dark/desaturated colours: kill hue noise
    if (sq === 0 || lq < 3) { hq = 0; }
    return (hq << 10) | (sq << 7) | lq;
  }

  // ---- frozen human AnimBase label banding (tools/anim_labels.json) ----
  // lines: [neck, shoulder, elbow, hip, knee, wrist] in voxel y (down).
  function labelFor(part, vy, L) {
    const [neck, , elbow, hip, knee, wrist] = L;
    switch (part) {
      case "head":
        return (neck >= 0 && vy >= neck - 1) ? 23 : 19;
      case "torso":
        if (hip >= 0 && vy >= hip) return 30;
        if (hip >= 0 && vy >= hip - 2) return 28;
        return 26;
      case "right_arm":
        if (elbow >= 0 && vy > elbow + 1 && wrist >= 0 && vy > wrist) return 7;
        if (elbow >= 0 && vy > elbow + 1) return 4;
        if (elbow >= 0 && vy >= elbow) return 2;
        return 3;
      case "left_arm":
        if (elbow >= 0 && vy > elbow + 1 && wrist >= 0 && vy > wrist) return 6;
        if (elbow >= 0 && vy > elbow + 1) return 5;
        if (elbow >= 0 && vy >= elbow) return 1;
        return 0;
      case "right_leg":
        if (knee >= 0 && vy > knee + 1) return 17;
        if (knee >= 0 && vy >= knee) return 35;
        if (hip >= 0 && vy <= hip + 1) return 32;
        return 38;
      case "left_leg":
        if (knee >= 0 && vy > knee + 1) return 18;
        if (knee >= 0 && vy >= knee) return 37;
        if (hip >= 0 && vy <= hip + 1) return 33;
        return 40;
      case "weapon_main": return 43;
      case "weapon_off": return 44;
      case "wings": return 26;
      case "tail": return 30;
      default: return 26;
    }
  }
  // feet rows override (bottom of legs)
  function footFix(part, vy, groundY, lab) {
    if (part === "right_leg" && vy >= groundY - 2) return 13;
    if (part === "left_leg" && vy >= groundY - 2) return 15;
    return lab;
  }

  // ---- voxel part -> geometry arrays ----
  // Model space: x right (sign flips mirror), y down (LC y is negative-up, so
  // up = smaller vy = more negative model y), z depth. Orientation constants
  // verified in-game against the sprite turnaround.
  // 180° about vertical vs the raw grid: the sprite's south (front) surface
  // must face the camera when the entity yaw says "south" (verified in-game)
  const X_SIGN = -1, Z_SIGN = 1;

  // 6-byte records [x,y,z,r,g,b] — full-fidelity reference-process voxels,
  // colours exactly as the sprite8 optimizer seeded them
  function decodePart(p) {
    const bin = atob(p.vox6);
    const n = (bin.length / 6) | 0;
    const vox = new Map();
    for (let i = 0; i < n; i++) {
      const o = i * 6;
      const rgb = (bin.charCodeAt(o + 3) << 16) | (bin.charCodeAt(o + 4) << 8) | bin.charCodeAt(o + 5);
      vox.set(bin.charCodeAt(o) | (bin.charCodeAt(o + 1) << 8) | (bin.charCodeAt(o + 2) << 16), rgb);
    }
    return vox;
  }

  function buildBaseModel(data) {
    const [cw] = data.canvas;
    const groundY = data.ground_y;
    const L = data.lines;
    // pre-scan extents: these sprites are chibi-proportioned (nearly as wide
    // as tall), so fit BOTH height and width against LC humanoid bounds or
    // the character becomes a giant slab next to the LC NPCs
    let vx0 = 1e9, vx1 = -1e9;      // body extent (wings/weapons overhang freely)
    let ax0 = 1e9, ax1 = -1e9;      // full extent (for centring)
    const decoded = {};
    const globalVox = new Set();   // union across parts: exposure tests use
                                   // this so inter-part faces are never emitted
    for (const [part, p] of Object.entries(data.parts)) {
      const vox = decodePart(p);
      decoded[part] = vox;
      const bodyPart = part !== "wings" && !part.startsWith("weapon");
      for (const key of vox.keys()) {
        globalVox.add(key);
        const x = key & 0xff;
        if (x < ax0) ax0 = x;
        if (x > ax1) ax1 = x;
        if (bodyPart) {
          if (x < vx0) vx0 = x;
          if (x > vx1) vx1 = x;
        }
      }
    }
    if (vx0 > vx1) { vx0 = ax0; vx1 = ax1; }
    const wvox = Math.max(8, vx1 - vx0 + 1);
    const scale = Math.min(190 / Math.max(8, data.height_vox), 120 / wvox);
    const cx = (vx0 + vx1) / 2;

    const vx = [], vy = [], vz = [], vlab = [];
    const fa = [], fb = [], fc = [], finfo = [], fcolA = [], fcol = [];
    const vmap = new Map(); // welded per (part-label bucket): key -> index

    const addV = (x, y, z, lab) => {
      const key = `${x},${y},${z},${lab}`;
      let i = vmap.get(key);
      if (i === undefined) {
        i = vx.length;
        vmap.set(key, i);
        vx.push(Math.round((x - cx) * scale) * X_SIGN);
        vy.push(Math.round((y - (groundY + 1)) * scale));
        vz.push(Math.round((z - cw / 2) * scale) * Z_SIGN);
        vlab.push(lab);
      }
      return i;
    };

    // Greedy meshing: per part, per face direction, per slice, merge exposed
    // faces of identical (colour, label) into maximal rectangles — keeps the
    // model well under the engine's static vertex/face scratch limits.
    // dir spec: a = slice axis (0=x 1=y 2=z), plane = face at slice+plane,
    // u/v = the in-plane axes, corners = winding template (components 0/1
    // per axis: a-axis -> slice+plane, u -> u0/u1+1, v -> v0/v1+1).
    const DIRS = [
      { a: 1, plane: 0, u: 0, v: 2, n: [0, -1, 0], sh: 1.05, cw: [[0, 0], [0, 1], [1, 1], [1, 0]] },   // top
      { a: 1, plane: 1, u: 0, v: 2, n: [0, 1, 0], sh: 0.62, cw: [[0, 0], [1, 0], [1, 1], [0, 1]] },   // bottom
      { a: 0, plane: 0, u: 1, v: 2, n: [-1, 0, 0], sh: 0.88, cw: [[0, 0], [1, 0], [1, 1], [0, 1]] },   // -x
      { a: 0, plane: 1, u: 1, v: 2, n: [1, 0, 0], sh: 0.88, cw: [[0, 1], [1, 1], [1, 0], [0, 0]] },   // +x
      { a: 2, plane: 0, u: 0, v: 1, n: [0, 0, -1], sh: 1.0, cw: [[1, 0], [1, 1], [0, 1], [0, 0]] },   // -z
      { a: 2, plane: 1, u: 0, v: 1, n: [0, 0, 1], sh: 0.8, cw: [[0, 0], [0, 1], [1, 1], [1, 0]] },   // +z
    ];
    // Winding: LC culls screen-CCW faces; in model space the convention
    // (measured on the stock body-kit models) is geometric normal =
    // cross(B-A, C-A) pointing OUTWARD. The X/Z sign flips change handedness,
    // so compute per-direction whether the corner template needs reversing.
    for (const dir of DIRS) {
      const pos = dir.cw.map(([cu, cv]) => {
        const co = [0, 0, 0];
        co[dir.a] = dir.plane;
        co[dir.u] = cu;
        co[dir.v] = cv;
        return [co[0] * X_SIGN, co[1], co[2] * Z_SIGN];
      });
      const u = [pos[1][0] - pos[0][0], pos[1][1] - pos[0][1], pos[1][2] - pos[0][2]];
      const w = [pos[2][0] - pos[0][0], pos[2][1] - pos[0][1], pos[2][2] - pos[0][2]];
      const n = [u[1] * w[2] - u[2] * w[1], u[2] * w[0] - u[0] * w[2], u[0] * w[1] - u[1] * w[0]];
      const o = [dir.n[0] * X_SIGN, dir.n[1], dir.n[2] * Z_SIGN];
      dir.flip = n[0] * o[0] + n[1] * o[1] + n[2] * o[2] < 0;
    }
    const emitRect = (dir, slice, u0, v0, u1, v1, hsl, lab) => {
      let q = dir.cw.map(([cu, cv]) => {
        const co = [0, 0, 0];
        co[dir.a] = slice + dir.plane;
        co[dir.u] = cu ? u1 + 1 : u0;
        co[dir.v] = cv ? v1 + 1 : v0;
        return addV(co[0], co[1], co[2], lab);
      });
      if (dir.flip) q = [q[0], q[3], q[2], q[1]];
      fa.push(q[0], q[0]);
      fb.push(q[1], q[2]);
      fc.push(q[2], q[3]);
      for (let t = 0; t < 2; t++) { finfo.push(1); fcolA.push(hsl); fcol.push(hsl); }
    };

    for (const [part, p] of Object.entries(data.parts)) {
      const vox = decoded[part];
      const K = (x, y, z) => x | (y << 8) | (z << 16);
      for (const dir of DIRS) {
        const di = DIRS.indexOf(dir);
        const hslCache = new Map();  // rgb -> hsl16 for this direction's shade
        // collect exposed faces of this direction, grouped by slice
        const slices = new Map(); // slice -> Map("u,v" -> tag) where tag = hsl<<8|label-ish
        const tags = new Map();   // tagId -> {hsl, lab}
        let nextTag = 1;
        const tagIds = new Map(); // "hsl,lab" -> tagId
        for (const [key, rgb] of vox) {
          const co = [key & 0xff, (key >> 8) & 0xff, (key >> 16) & 0xff];
          const nb = [co[0] + dir.n[0], co[1] + dir.n[1], co[2] + dir.n[2]];
          if (nb[0] >= 0 && nb[1] >= 0 && nb[2] >= 0 && globalVox.has(K(nb[0], nb[1], nb[2]))) continue;
          let hsl = hslCache.get(rgb);
          if (hsl === undefined) { hsl = rgbToHsl16(rgb, dir.sh); hslCache.set(rgb, hsl); }
          const lab = footFix(part, co[1], groundY, labelFor(part, co[1], L));
          const tk = hsl + "," + lab;
          let tid = tagIds.get(tk);
          if (tid === undefined) { tid = nextTag++; tagIds.set(tk, tid); tags.set(tid, { hsl, lab }); }
          const s = co[dir.a];
          let m = slices.get(s);
          if (!m) { m = new Map(); slices.set(s, m); }
          m.set(co[dir.u] + "," + co[dir.v], tid);
        }
        for (const [s, m] of slices) {
          const done = new Set();
          for (const [uv, tid] of m) {
            if (done.has(uv)) continue;
            const [u0, v0] = uv.split(",").map(Number);
            // extend along u
            let u1 = u0;
            while (m.get((u1 + 1) + "," + v0) === tid && !done.has((u1 + 1) + "," + v0)) u1++;
            // extend along v while the whole u-run matches
            let v1 = v0;
            outer: while (true) {
              for (let u = u0; u <= u1; u++) {
                const k = u + "," + (v1 + 1);
                if (m.get(k) !== tid || done.has(k)) break outer;
              }
              v1++;
            }
            for (let u = u0; u <= u1; u++) for (let v = v0; v <= v1; v++) done.add(u + "," + v);
            const t = tags.get(tid);
            emitRect(dir, s, u0, v0, u1, v1, t.hsl, t.lab);
          }
        }
      }
    }

    const model = new LC.Model({
      vertexCount: vx.length,
      vertexX: Int32Array.from(vx),
      vertexY: Int32Array.from(vy),
      vertexZ: Int32Array.from(vz),
      faceCount: fa.length,
      faceVertexA: Int32Array.from(fa),
      faceVertexB: Int32Array.from(fb),
      faceVertexC: Int32Array.from(fc),
      faceColorA: Int32Array.from(fcolA),
      faceColorB: Int32Array.from(fcolA),
      faceColorC: Int32Array.from(fcolA),
      faceInfo: Int32Array.from(finfo),
      facePriority: null,
      faceAlpha: null,
      faceColor: Int32Array.from(fcol),
      priority: 0,
      texturedFaceCount: 0,
      texturedVertexA: new Int32Array(0),
      texturedVertexB: new Int32Array(0),
      texturedVertexC: new Int32Array(0),
      vertexLabel: Int32Array.from(vlab),
    });
    model.createLabelReferences();
    model.calculateBoundsCylinder();
    return model;
  }

  // ---- synthetic "NpcType": lets NpcEntity/PlayerEntity-style draw paths
  // animate the paperdoll through the stock getSequencedModel contract ----
  function typeFor(folder) {
    const safe = safeName(folder);
    let entry = modelCache.get(safe);
    if (entry) return entry.type;
    const data = PAPERDOLL_DATA[safe];
    if (!data) return null;
    const base = buildBaseModel(data);
    const type = {
      size: 1,
      paperdoll: true,
      getSequencedModel(primaryTransformId, secondaryTransformId, seqMask) {
        const tmp = LC.Model.modelShareAlpha(base, true);
        if (primaryTransformId !== -1 && secondaryTransformId !== -1) {
          tmp.applyTransforms(primaryTransformId, secondaryTransformId, seqMask);
        } else if (primaryTransformId !== -1) {
          tmp.applyTransform(primaryTransformId);
        }
        tmp.calculateBoundsCylinder();
        tmp.labelFaces = null;
        tmp.labelVertices = null;
        tmp.pickable = true;
        return tmp;
      },
    };
    modelCache.set(safe, { type, base });
    return type;
  }

  return { load, available, typeFor, safeName, get data() { return PAPERDOLL_DATA; } };
})();
